ProjectTing/Ting

Ting/Search/SearchSelectModal.swift, Ting/Search/SearchSelectModalVC.swift, Ting/Search/SearchV.swift, Ting/Search/SearchVC.swift, Ting/Search/SearchView.swift
- 기존 서치뷰에 커스텀 컬러, 태그버튼 적용
- 버튼액션 로직 뷰컨으로 이동
- 태그 길이 조정
- 커스텀컬러, 태그버튼 적용
- 태그 길이 조정
- 태그 타이틀 색상 고민 (스크린샷 참고)
- 구인/구직 : .brownText
- 직무 : .primary
- 검색 시 어떤 태그 넣을지 ( 현재 임시상태)
- 적용하기 버튼 모양, inset 고민
Resolves: #30
=> Feat: 서치뷰 커스텀 컬러, 태그 적용

Ting/MyPage/DeleteInfoVC.swift, Ting/MyPage/EditCustomView.swift, Ting/MyPage/EditInfoVC.swift, Ting/MyPage/MyPageCustomVIew.swift, Ting/MyPage/MyPageMainVC.swift
- 카드뷰 두 개로 나누어 구현
- 커스텀 뷰 생성하여 label들을 생성할 때 코드를 간결하게 하고 코드의 재사용성을 높임
- 버튼 액션으로 회원정보 수정 및 회원탈퇴 뷰로 연결
- 버튼 색 변경
- 폰트 변경
Resolves: #36
-----
- TextFiled의 테두리를 추가하고 색을 변경했습니다
- placeholder의 색을 변경했습니다.
- 저장하기 버튼 클릭시 마이페이지로 돌아가게 구현하였습니다.
- TextField 바깥의 다른곳을 탭하면 키보드가 내려가게 하였습니다.
- 입력을 마치고 return키를 클릭하면 키보드가 내려가게 하였습니다.
- 수정 취소 버튼?
- 수정완료 얼럿 띄우고 확인시 이동
- 클리어버튼 색상 변경 (커스텀에서 확인)
Resolves: #34
-----
- 글자들의 크기를 변경했습니다.
- 버튼의 색을 변경했습니다
- 체크 버튼을 만들어서 회원 탈퇴에 동의한다는 것을 확인받도록 했습니다.
- 체크아이콘 클릭시에만 탈퇴 버튼 활성화
Resolves: #35
=> Feat: MyPage, 회원정보 수정, 탈퇴 UI 구현 완료

Ting/Search/SearchVC.swift, Ting/Search/SearchView.swift
- 서치뷰 컬렉션뷰에 셀 적용
- 셀 적용
- 메인뷰 셀 모양 변경 시 코드 수정 필요
- 검색 전 화면 처음 **진입 시 셀 데이터 0개, 검색 이후 적용 기능** 구현 필요 (서버연결 이후)
- 필터 적용 후 **검색에 필터적용되는 기능** 구현 필요
- 적용한 **필터 필터설정 옆으로 or 아래에 태그 생기게** 기능 구현 필요
Resolves: #47
=> Feat: 서치뷰에 메인뷰 셀 적용

Ting/Post/ReportVC.swift
- reasonCardView 제약조건 변경
- ReportVC 뷰 전체 스크롤뷰 적용
- reasonCardView 라디오버튼 객체 터치 이슈 해결
- ReportVC 뷰 전체 스크롤뷰 적용을 통한 터치id, 노치 기기 화면짤림 현상 해결 및 레이아웃 지원
- 임의값 240으로 제약조건 수정했지만 실기기 테스트에서 수정이 필요할 수 있음
- 영진님 파트 수정에 따른 코드 수정 및 적용 필요
Resolves: #66
=> Fix : 라디오버튼 제약조건 수정 및 터치id 기기 레아이웃 적용

Ting/SignUp/SignUpView/PermissionView.swift, Ting/SignUp/SignUpView/SignUpViewController.swift, Ting/SignUp/SignUpView/TermsCell.swift, Ting/SignUp/SignUpView/TermsModalVC.swift
- 약관 동의 View 텍스트 수정 
- (선택) 약관 삭제
- 만 14세 이상 약관 토글 제거
- (필수) 약관 모두 동의를 해야만 다음으로 진행 가능
- 동의 모달 닫은 후 애플 로그인 View로 이동
- 로그인 완료 후 TabBar 이동
- 토글 클릭 시 약관 안내로 이동
-  약관 동의 데이터 메모리 (자동 로그인 구현과 연계 예정)
-  런치 스크린..?
Resolves: #98
=> Feat: 약관 동의, 회원가입 완료 후 탭바로 이동

Ting/AppDelegate.swift, Ting/SceneDelegate.swift, Ting/SignUp/SignUpView/SignUpViewController.swift
- AppDelegate에서 SceneDelegate로 앱 화면 별 루트 뷰 컨트롤러 이동.
- 애플 로그인 완료 후 AddInfoVC로 이동
- 첫 사용자 : 앱 실행 시 회원가입을 위한 약관 동의 뷰 진입 » 동의 후 애플 로그인 뷰 진입 » 로그인 완료 후 AddInfoVC로 이동
- 가입 완료 유저 : 앱 실행 시 바로 TabBar로 이동
.
- AppDelegate, SceneDelegate를 수정했기 때문에 개인 작업을 하시기 위해서, 주석 처리 후 루트 뷰 컨트롤 변경이 필요합니다.
- 약관 작성..
Resolves: #100 
Resolves: #105
=> Feat: 루트 뷰 컨트롤러 조정 및 구현

Ting/API/PostService.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift
- Nickname값에 따른 버튼출력 뷰 수정
- 닉네임 값에 따라서 버튼출력
- Delete 기능 구현
- DetailVC에서 Nickname값 대조해서 작성자와 보는사람의 닉네임이 동일하면 편집하기버튼이, 불일치하면 신고하기 버튼 기능 구현
- 기존에는 신고하기, 편집하기 버튼이 같이 떴지만 이제 하나의 버튼만 출력, 또한 UploadVC의 디자인처럼 적용
- 삭제하기 버튼 터치시 정말 삭제할거냐는 alert뜬 다음에 확인 버튼 누를시 실제 데이터 삭제 기능 적용
- Nickname 구별값이 없어서 해당기능 구현
- 이후 닉네임 하드코딩된거 전체 수정작업 필요
Resolves: #103
=> Feat : DetailVC 추가기능 구현

Ting/MyPage/DeleteInfo/DeleteInfoVC.swift, Ting/SignUp/SignUpView/SignUpViewController.swift
- 회원 탈퇴 미동의시 탈퇴하기 버튼 비활성화
- AddInfoVC를 AddUserInfoVC로 이동 및 이름 변경
- 회원 탈퇴 버튼을 누르면 첫 화면 PermissonVC로 이동
- 동시에 Firebase, Firestore에 저장돼있는 데이터 삭제
.
- 회원 탈퇴 약관 작성 필요(?)
- 약관 작성
Resolves: #109
=> Feat: 회원 탈퇴시 데이터 삭제 구현

Ting/Models/UserInfo.swift, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/SceneDelegate.swift, Ting/SignUp/SignUpView/SignUpViewController.swift
- SignUpViewController에서 새로운 유저 확인용 고유키값 id 생성 및 저장
- 이후 AddUserInfoVC에서 해당 값이 넘어가 userID라는 값으로 저장이됨
- Nickname을 고유 키값으로 사용하기 위한 닉네임 중복검증 필요
- 기능 구현을 위한 SceneDelegate 수정
- SignUpViewController 파일 수정
- AddUserInfoVC 파일 수정
- UserInfo 파일 수정
- 로그인 상태값에 따라 로그인이 안된상태는 SignUpViewController로, 로그인이 된 상태는 메인으로 넘어가게  SceneDelegate 로직 수정
- SignUpViewController 애플 로그인 시 회원고유 키값 생성
- 생성된 고유 키값은 AddUserInfoVC로 넘어갈때 같이 넘어가져서 해당 컬렉션에 값이 값 저장
- 생성된 고유 키값을 생성, 사용하기 위한UserInfo 파일 수정
- Nickname을 고유 키값으로 사용하기 위한 닉네임 중복검증 필요
- 현재는 회원가입으로만 테스트를 했는데 신규 기기로 로그인시, 혹은 로그아웃 된 상태에서 신규 생성이 되는지 안되는지 테스트 필요
Resolves: #110
=> Feat : SignUpViewController 새로운 고유구별값 적용 및 회원가입, 정보기입시 적용

Ting/CustomView/CustomTag.swift, Ting/Main/MainView/MainVC.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift
- UI : 태그버튼 clipsToBounds 적용, 메인 세로스크롤 적용 ( 작은기기 대응)
- 작성하기, 수정하기 이후 리스트 새로고침 delegate로 로직 변경 ( listDelegate )
- 기존 태호님이 구현해주신 delegate -> updateDelegate로 변경
- listDelegate 추가
- 위와 동일
- 수정 이후 서버에서 데이터 받아와야 할듯
- 삭제 기능 추가 필요
- 메인 셀 클릭시에도 동일적용 필요
Resolves: #164
=> Fix: 작성,수정시 게시글리스트 새로고침 delegate 추가, UI 일부 수정

Ting/MyPage/DeleteInfo/DeleteInfoVC.swift, Ting/MyPage/MyPageMain/MyPageMainVC.swift, Ting/SceneDelegate.swift, Ting/SignUp/SignUpView/SignUpVC.swift, Ting/SignUp/SignUpView/SignUpView.swift
- 비회원 로그인을 구현했습니다.
- 버튼의 위치는 애플로그인 하단에 배치했습니다.
- `SignUpViewController`클래스의 이름을 변경하였습니다. -> `SignUpVC`
- 로그아웃 시 이동되면 화면을 `SignUpVC`로 변경하였습니다
- 비회원 로그인을 클릭 시, 로그인 없이 메인화면으로 넘어가게 구현하였습니다.
- 클래스 이름을 변경하면서, 해당 이름을 사용하던 부가적인 코드도 전부 변경하였습니다.
- 비회원일 때, 게시글 작성, 신고, 회원정보 수정 등을 하지 못하도록 로직처리가 필요합니다.
- 비회원일 때, 마이페이지에 접근하지 못하도록 하는 로직이 필요합니다.
Resolves: #161
=> Feat: 비회원 로그인 구현

Ting/Extension/LoginCheck+Alert.swift, Ting/MyPage/DeleteInfo/DeleteInfoVC.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift
- 편집하기 -> 수정하기로 작성뷰 진입 시 버튼 타이틀 바뀌도록 수정
- 탈퇴 시 UserDefaults 삭제 추가
- 비회원일 경우 알럿 확인 이후 화면 이동 방식 수정
- detailVC에서 delegate -> viewWillAppear로 변경에 따른
listVC에 기존 사용하던 불필요한 delegate 코드 삭제 및 listDelegate -> delegate로 다시 변경
- 게시글 삭제 시 새로고침 기능 추가
- 회원 탈퇴 시에도 UserDefaults 의 userId 삭제 코드 추가
- loginCheck 메서드 내에서 확인 눌렀을 때 모달 present 가 아닌 
sceneDelegate.window?.rootViewController를 새로 할당
이전 방식은 메모리가 남아있을 수 있기에 해당 방식으로 변경. ( 초기화 )
- 수정 시 리스트 새로고침은 삭제함.
( 수정 시 리스트로 돌아오는 것이 아니기에 바로 적용이 안되어 삭제 )
Resolves: #173
=> Fix: 수정하기 버튼타이틀, 탈퇴시 UserDefaults 삭제, 비회원 화면이동 수정

Ting/SignUp/SignUpView/SignUpVC.swift, Ting/SignUp/SignUpView/TermsModalVC.swift
- OAuthProvider 경고문 삭제
- PresentingVC 변수 선언 삭제
- presentingVC에서 변수를 선언했지만 사용하지 않아 Xcode에서 경고 ➡️ 여전히 값이 nil인지 확인하지만, 새 변수를 선언하지 않음.
- Firebase가 OAuth 인증 구조를 업데이트 ➡️ 명시적으로 nil 전달
- providerID가 string이 아니라 AuthProviderID 타입 필요 ➡️ AuthProviderID.apple 사용
.
- 하이라키, 기타 버그 확인
Resolves: #179
=> Fix: 경고문 삭제 (OAuth 인증 구조)

Ting/Post/PostView/PostListVC.swift, Ting/Search/SearchView/SearchView.swift
- 에러처리 일부 수정
- 알럿에 error.localizedDescription 삭제
- 사용자에게 보여지는 것이 안좋다 하여 삭제했습니다.
- 검색필터 스크롤뷰 레이아웃 문제 수정
=> Fix: 에러처리 일부수정, 스크롤뷰 레이아웃 수정

Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
- 폰트 컬러 blue ➡️ gray
- 텍스트 밑줄 생성
- 회원탈퇴 약관 버튼의 폰트 컬러 변경 및 밑줄 적용
.
Resolves: #187
=> Feat: 회원탈퇴 약관 버튼 수정

Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/ReportVC.swift
- DetailVC 데이터 출력을 위한 뷰 디자인 및 각 영역 배치 수정 작업
- ReportVC 데이터 출력을 위한 뷰 수정 및 오류수정
- 뷰 출력수정 및 배치수정
- 제목 길어질 시 자동으로 아랫줄로 줄변경 기능 추가
- 제목 하단의 작성자 닉네임 출력
- UploadVC에서 값은 받지만 미출력하던 내용들 출력
- UploadVC에서 받은 값에 따라 출력하는 내용, 라벨 다르게 수정
- 기술스택, 제목 하단 태그 제외 부분들은 중간에 라벨 - 텍스트 순으로 출력되게 정렬
- 카드뷰 밖으로 신고/편집하기 버튼 출력
- 신고 게시글 제목이 길어질 시 자동으로 아랫줄로 늘어나게 수정
- 라디오 버튼 수정전 기존코드로 원복
- 중복체크 되던 현상 해결
- 이상하게 출력되던 현상 수정
Resolves : #191
=> Feat/Fix : DetailVC 뷰 배치 및 디자인 수정 및 조정, ReportVC 신규기능 추가 및 오류수정

Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift
- DetailVC 파일 수정
- 제목 하단 태그 포지션 출력
- 태그 중복출력 해결
- 모집/합류에 따라서 필요한 직무 출력 조정
- 모집/합류에 따라서 필요 기술 스택/ 보유 기술 스택 출력값 구분
=> Fix : DetailVC 뷰 객체 추가 및 조정

Ting/API/UserInfoService.swift, Ting/Models/UserInfo.swift, Ting/Post/PostView/ReportVC.swift
- UserInfoService, UserInfo, ReportVC 파일 수정
- ReportVC에서 신고하기 버튼 터치 시 infos에 신고 게시글 id 배열로 저장
- 신고하기 중첩 누적시 자동 삭제기능?
- 신고하기 여러번 적용된 사용자는 기능제한? 벤? 기능 구현
Resolves: #206
=> Feat : ReportVC 신고하기 버튼 시 infos에 신고데이터 배열 업데이트

Ting/API/PostService.swift, Ting/Models/Post.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift, Ting/Post/PostView/ReportVC.swift
- 신고하기 버튼 터치 시 해당 게시글의 신고하기 횟수 자동 카운트 기능 구현
- 신고 누적 5회가 된 게시글의 경우에 자동으로 삭제되게 기능 구현
- PostSevice 파일 수정
- 게시글 신고 카운트 메서드 구현
- Post 파일 수정
- 신고횟수 카운트 값 세팅
- JoinTeamUploadVC
- 신고횟수 카운트 값 세팅
- RecruitMemberUploadVC
- 신고횟수 카운트 값 세팅
- ReportVC
- 신고 하기 버튼 터치시 신고당하는 게시글의 신고카운트 증가 기능 구현
- 누적 신고 5회시 자동으로 해당게시글 삭제기능 구현
- 마무리 일격? 을 날린 사용자에게 마지막 누적 신고로 인한 삭제되었다고 얼럿 추가내용 삽입
Resolves: #212
=> Feat : 신고하기 버튼 터치 시 해당 게시글의 신고하기 횟수 증가 및 5회인 경우에 해당 게시글은 자동 삭제

Ting/API/SlackService.swift, Ting/Post/PostView/ReportVC.swift
- 게시글 신고 발생 시, 개발진 슬랙으로 메시지를 전송하도록 구현하였습니다.
- 게시글 전송 봇을 만들었고, 다른 서버를 거치지 않고 앱에서 바로 봇으로 메시지를 보내도록 구현하였습니다.
- 해당 기능으로 다른 주요 상황에서도 개발진 슬랙으로 메시지를 보낼 수 있도록 고민
Resolves: #214
=> Feat: 게시글 신고 접수 시, 슬랙으로 메시지를 전송

Ting/Info.plist, Ting/Post/PostView/PostDetailVC.swift
- 태그 수정시 겹치는 문제 해결
- 다크모드 미적용으로 변경
- 
-
-
- 
- 
Resolves: #이슈번호
=> Fix: 다크모드 지원x, 기술태크 겹침문제해결

Ting/API/PostService.swift, Ting/CustomView/BaseUploadView.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/JoinTeamUploadView.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift, Ting/Post/PostView/RecruitMemberUploadView.swift, Ting/Post/PostView/ReportVC.swift
- 게시글 작성페이지 UX 관련 수정
- 게시글 리스트 새로고침 delegate -> Notification 으로 변경
- 최근게시글 10개 불러온뒤 거르는 방식으로 변경
- 텍스트필드 done 버튼 클릭 시 키보드 내리기
- 기술스택 글자수 제한
- 텍스트뷰 줄바꿈, 글자수 제한
- 작성페이지 버튼 오토레이아웃 수정 ( 화면 늘어날 시 보이도록 )
- 차단기능 로그인 검증 추가
- 게시글 리스트 새로고침 delegate -> Notification 으로 변경
- 최근 게시글 관련 신고, 차단 시 메인에서 3개가 안보여지는 현상으로
10개 불러온 후 걸러내는 방식으로 변경
- UX 관련 수정하였으나 테스트 필요
- 새로고침 관련 delegate로 하려다 보니 복잡하여 Notification으로 하니 간단해짐
- 최근게시글 10개 불러오는 방식이 올바른지 고민 필요 ( 서버 사용량 관련 )
- 노티피케이션 추가하면서 ListVC에 두개의 알림 등록이 되어있는데
해당 부분은 추후 더 학습해보면 좋을 것 같습니다.
Resolves: #이슈번호 추가예정
=> Fix: 게시글 작성, 리스트 1.0.3 피드백 관련 수정

Ting/SignUp/SignUpView/TermsCell.swift, Ting/SignUp/SignUpView/TermsModalVC.swift
- updateAllAgreeButtonState()를 호출하여 "모두 동의" 상태를 동기화.
- onCheckToggle을 isCheckd.toggle()과 연동하여 즉시 반영.
- "모두 동의" 버튼이 정확히 동작하지 않아 각 상태를 동기화
- 개별 체크가 가끔 풀리지 않거나 동의 체크가 되지 않아 토글을 연동하고, 체크 아이콘과 텍스트 클릭을 하나로 통합해 둘 중 어디를 눌러도 정확하게 체크되도록 수정.
- 아이콘, 텍스트 통합 후 약관 URL로 이동되지 않아 이동 버튼에 별도의 터치 이벤트 설정.
.
- 회원가입 약관 동의 이탈 이슈
- 기타 버그 확인
Resolves: #240 
Resolves: #241
=> Feat: 약관 동의, 약관 URL 이동 수정

Ting.xcodeproj/project.pbxproj, Ting/Extension/SpacesAndSpecialChar.swift, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/EditInfo/EditInfoVC.swift, Ting/MyPage/MyPageMain/MyPageMainVC.swift
- 기존 로직을 사용해서 닉네임 이외의 택스트필드들도 공백, 특수문자 검증을 구현하였습니다.
- 기술 스택, 사용 툴, 관심사 같은 필드는 공백 및 특수문자가 필요하므로, 
첫 글자를 공백으로 작성하여 빈 값을 만드는 것을 방지하기 위해
첫글자가 공백인지 아닌지만 검사하도록 로직을 새로 구현하고 적용시켰습니다.  
- 협업 방식과 직군 필드는 공백과 특수문자가 필요없으므로 공백, 특수문자 모두 적용시켰습니다.
Resolves: #245
=> Feat: 닉네임 이외 텍스트필드 공백, 특수문자 검증 로직 구현

Ting/SignUp/SignUpView/PermissionVC.swift, Ting/SignUp/SignUpView/SignUpVC.swift
- SignUpVC에서 저장하던 약관 동의 데이터를 PermissionVC로 이동.
- PermissionVC에서의 termsAccepted 약관을 Firestore users에 저장합니다.
.
- 기타 버그 확인
Resolves: #248
=> Fix: 약관 미동의 후 앱 재접속시 넘어가는 버그 수정

Ting/Main/MainView/MainViewCell.swift, Ting/SignUp/SignUpView/SignUpVC.swift
- merge: true 코드 추가
- 영진님 메인뷰 셀 UI 수정
- "merge: true" 사용으로 Firestore에서 기존 필드는 유지하면서 새로운 데이터만 추가
- UI 수정
.
- 버그 확인 및 수정
- 
- 
Resolves: #251
=> Fix: 로그아웃, 종료 후 약관 동의 데이터 사라지는 버그 수정

.gitignore, Ting.xcodeproj/project.pbxproj, Ting/API/SlackService.swift, Ting/MyPage/EditInfo/EditInfoVC.swift
- 기존 Slack Webhook URL이 깃허브에 같이 올라가면서, 오픈되어서 Slack측에서 자동으로 밴을 시키는 현상 발생
결과 -> 코드와 로직은 있지만 WebhookURL 값이 없기 때문에 작동하지 않음.
- Webhook URL을 별도의 파일로 분리하고, 이그노어에 추가하는 등, 추적되지 않도록 수정
- 게시글 신고시 개발팀 슬랙으로 정상적으로 봇이 메시지를 전송함.
-----------
Resolves: #260
=> Fix: 신고 발생시 슬랙 알림이 오는 기능 관련 수정
