ProjectTing/Ting

Ting/Main/MainVC.swift, Ting/MyPage/DeleteInfoVC.swift, Ting/MyPage/EditInfoVC.swift, Ting/MyPage/MyPageMainVC.swift, Ting/Post/PostDetailVC.swift, Ting/Post/PostMainVC.swift, Ting/Post/PostUploadVC.swift, Ting/Post/ReportVC.swift, Ting/Search/SearchResultVC.swift, Ting/Search/SearchVC.swift
=> Feat: 각 역할별 VC 생성

Ting/SignUp/SignUpViewController.swift
제가 구현할 파트라 코드 구현까지 아주 조금 진행했습니다.
=> feat: 회원가입 뷰 생성

Ting/TestFile/TestModels/TestPost.swift, Ting/TestFile/TestPostUploadVC.swift, Ting/TestFile/TestPostVC.swift, Ting/TestFile/TestServices/TestPostService.swift
- 게시글 작성 버튼 클릭 시 : 선택, 작성한 내용 Firebase 서버 (Cloud FireStore) 내 Firestore Database 에 Create
- 테스트 보기 or 작성 후 : Database에 저장된 게시글 최근 1개를 Read 후 카드 형태의 테스트 뷰에 적용 
Resolves: #17
=> feat: 파이어베이스 C,R 테스트

Ting/SceneDelegate.swift, Ting/TestFile/TestPostDetailVC.swift, Ting/TestFile/TestPostUploadVC.swift, Ting/TestFile/TestPostVC.swift
=> Feat : 테스트 포스트 -> 디테일뷰간 테스트 연결 및 기능 테스트

Ting/Main/MainVC.swift, Ting/SceneDelegate.swift, Ting/Search/SearchVC.swift, Ting/TabBar/TabBar.swift
하단 탭바를 구현하였으며, 각 아이템은 컬러코드에 따라 색상이 적용되었습니다.
현재 아이콘과 탭바 아이템이 선택되었을 때의 아이콘은 추후 수정이 필요합니다. 
임시로 임의의 뷰들을 연결해 두었습니다. 🎨
- 하단 탭바 구현 완료 ✅
- 컬러코드에 따른 색상 적용 🎨
- 각 탭바 아이템에 임시로 뷰 연결 🔗
- 아이콘 및 탭바 아이템 선택 시 아이콘 수정 🔄
---
이슈 번호 : #21
=> Feat: 하단 탭바 구현

Ting/SignUp/FirstView.swift, Ting/SignUp/FirstViewController.swift, Ting/SignUp/SignUpView.swift, Ting/SignUp/SignUpViewController.swift, Ting/SignUp/TermsCell.swift, Ting/SignUp/TermsView.swift, Ting/SignUp/TermsViewController.swift
****
****
Resolves #24  
Resolves #40
=> Feat: 약관 동의 모달 창 구현

Ting/Main/MainVC.swift
서치바에서 검색뷰로 이동하지 않는 문제를 해결하였습니다.
=> Fix: 서치바에서 검색뷰로 이동하지 않는 문제 수정

Ting/Models/ReportModel.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/ReportVC.swift, Ting/Post/PostViewModel/ReportViewModel.swift
-  MVVM 패턴 추가
- PostDetailVC 화면 수정
- ReportVC MVVM패턴 적용 및 신규 적용된 폴더들에 배치 (기능 이상 무)
- 태그 길이에 따른 구별선 위치 자동 조절
- 
- PostDetailVC MVVM 패턴화 적용필요
- 파일내 주석 상세화 및 코드 고도화 필요
- ListVC 파이어베이스 연동 이후 DetailVC로 내부 데이터 및 값 연동후 출력기능 구현 필요(파이어베이스로 CRUD기능 구현)
- ListVC 터치시 해당 셀의 값 DetailVC로 출력(Read) 
- 로그인 값에 따라서 수정하기 버튼 나오게 구현
- 작성자와 같은 UniqueKey값이면 수정하기 버튼 등장(Read)
- 이후 UploadVC로 이동하면서 수정되기전  해당 내용들을 자동으로 셀에 출력(Read)
- 로그인 값에 따라서 신고하기 버튼 나오게 구현(Read)
- 작성자와 다른 UniqueKey값이면 신고하기 버튼 등장(Read)
- 위 내용을 기반으로 ReportVC 파이어베이스 연동 및 C,R 구현 필요 
- DetailVC의 신고대상자 닉네임, 신고대상 제목, 신고대상 작성일 데이터 가져와서 뷰 상단에 자동으로 띄우기(Read)
- 상단의 데이터들 및 신고사유 데이터, 상세내용 파이어베이스 서버내 저장 필요(Create)
Resolves: #72
=> Refactor : MVVM 패턴 추가

Ting/Models/Post.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/ReportVC.swift
- ReportVC 파이어베이스 연동
- ReportVC 에서 값 입력후 신고하기 버튼 터치 시 파이어베이스 서버에 저장
- Models 폴더안의 Post.swift 파일 수정한 인원은 컨플릭발생 할 수 있으니 파일 확인 필요
- detailVC의 값 다 가져오는지 체크 필요
- 체크항목, 상세내용에 빈값이 있을시 alert구현을 통한 사유 체크, 입력내용 기입시키게 하기 or 입력이 안되면 신고하기버튼 회색으로 비활성화
- 추후 todo를 위한 신고 처리여부 값 추가 필요(이건 앱 출시이후 고민 필요)
Resolves: #88
=> Feat : ReportVC 파이어베이스 연동

Ting/API/PostService.swift, Ting/CustomView/LabelAndTagSection.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift
- ListVC -> DetailVC데이터 연동
- DetailVC-> UploadVC 데이터 연동
- Update 기능 구현
- ListVC 에 있는 셀 터치시 임시 데이터가 아닌 서버에 연동된 값으로 DetailVC데이터 연동
- DetailVC 에서 수정하기 버튼 터치시 정해진 값에 맞게 팀원수정 or 팀모집 업로드 뷰로 이동, 또한 UploadVC로 이동간에 화면내 데이터 그대로 전달
- DetailVC를 통한 UploadVC 접근시 update 기능 구현
- 로그인 기능 구현에 따른 편집 <-> 삭제버튼 출력기능 구현
- rxswift를 안쓰더라도 서버내 신규 데이터가 갱신되면 자동으로 리스트랑 내용이 업데이트가 필요
Resolves: #96
=> Feat : ListVC -> DetailVC데이터 연동 + DetailVC-> UploadVC 데이터 연동

Ting/API/UserInfoService.swift, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/DeleteInfo/DeleteInfoVC.swift, Ting/MyPage/EditInfo/EditInfoVC.swift, Ting/SceneDelegate.swift, Ting/SignUp/SignUpView/PermissionVC.swift, Ting/SignUp/SignUpView/PermissionView.swift, Ting/SignUp/SignUpView/SignUpViewController.swift, Ting/SignUp/SignUpView/TermsModalVC.swift
- 닉네임 중복검증 적용
- EditInfoVC내 로직 추가
- AddUserInfoVC내 로직 추가
Resolves: #114
=> Feat : 닉네임 중복검증 적용

Ting/MyPage/MyPageMain/MyPageMainVC.swift
Fix: Navigation Bar 출력 안되는 문제 긴급 수정
Resolves: #122
=> Fix: Navigation Bar 출력 안되는 문제 긴급 수정

Ting.xcodeproj/project.pbxproj, Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
- 앱 지원 기기? 설정 - 아이폰만
- 가로모드 지원 x 설정
- 회원탈퇴 애플 재인증 추가
- 없음
Resolves: #129
=> Feat: 회원탈퇴시 애플 재인증 추가, 프로젝트 지원설정

Ting/API/PostService.swift, Ting/CustomView/TagFlowLayout.swift, Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift, Ting/Post/PostView/ReportVC.swift
- 상세페이지에서 수정 시 delegate 활용하여 새로고침
- 일부 주석 및 프린트문 삭제
- 기존 viewWillAppear 에서 새로고침하여
- 서버사용량 최소화를 위해 수정하기 버튼에서 delegate 활용
- 없음
Resolves: #141
=> Refactor, Cmt: 주석 수정 및 중복로직 삭제

Ting/Post/PostView/PostDetailVC.swift, Ting/Search/SearchView/SearchVC.swift
=> Fix: 검색관련 수정

Ting/API/UserInfoService.swift
- UserInfoService
- 닉네임 변경시 Posts에 저장된 닉네임도 같이 변경
- 닉네임 변경시 Reports에 저장된 닉네임도 같이 변경되게 기능구현
- Reports의 신고자 닉네임, 신고당한 닉네임의 구별값 세팅에 대한 고민 필요 
- 코드가 더럽기때문에 추후 해당부분 깔끔하게 리팩토링 필요
Resolves: #154
=> Feat : 닉네임 변경시 Posts에 저장된 닉네임도 같이 변경

Ting/API/ReportManager.swift, Ting/API/UserInfoService.swift
- ReportManager 파일 수정
- UserInfoService 파일 수정
- 회원정보 수정시 신고자, 신고작성자 닉네임 변경
Resolves: #157
=> Feat : 회원정보 수정시 신고자, 신고작성자 닉네임 변경

Ting/MyPage/DeleteInfo/DeleteInfoVC.swift, Ting/MyPage/MyPageMain/MyPageMainVC.swift, Ting/SceneDelegate.swift, Ting/SignUp/SignUpView/PermissionVC.swift, Ting/SignUp/SignUpView/SignUpVC.swift
- 각 뷰별 플로우 수정했습니다.
- Firestore userData 생성
- 앱 실행 시 첫 화면 ➡️ SignUpVC
- 애플로 로그인 완료 ➡️ PermissionVC
- 약관 동의 완료 ➡️ AddUserInfoVC
- 로그아웃 ➡️ SignUpVC
- 회원 탈퇴 ➡️ SignUpVC 
.
.
Resolves: #162
=> Feat: 앱 플로우 수정

Ting/API/PostService.swift, Ting/MyPage/EditInfo/EditInfoVC.swift, Ting/Post/PostView/PostDetailVC.swift
- PostService, PostDetailVC 수정
- EditIInfoVC 수정
- 수정하기 연속진행시 안되던 현상 수정
- 기존의 delegate 패턴에서 파이어베이스 서버로 다이렉트로 Update, Read 기능 구현
- 닉네임 수정하기 안먹히던 현상 수정
Resolves: #167
=> Fix : 수정하기 연속진행시 안되던 부분수정, 닉네임 수정하기 안먹히던 현상 수정

Ting/Extension/BasicAlert.swift, Ting/Extension/LoginCheck+Alert.swift, Ting/Main/MainView/MainVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/TabBar/TabBar.swift
- Extension 폴더 안에 LoginCheck+Alert 파일 내
비로그인 체크 후 알럿 띄우는 기능 구현
- 메인 셀 클릭 시 유저 확인 후 수정or편집 구분
- 로그인 시 UserDefaults에 저장하는 userId를 활용하여
이것이 없을 때 비로그인으로 간주하고 알럿을 띄우도록 함
- 알럿에서 확인 버튼 누를 시 로그인화면 띄움 ( SignUpVC )
- 해당 기능이 필요한 곳에서 guard self.loginCheck() else { return } 를 추가하면 될 것 같습니다.
- 메인 셀에도 유저확인 로직 추가
- 마이페이지, 신고하기 버튼에 비회원 체크 기능 추가
- 현재 방식이 적절한지 ( 유저디폴츠를 활용하는 것 )
- 확인버튼으로 이동될 경우 기존 화면들이 메모리에 남아있는 것이 영향을 미치진 않을지 ? 잘 모르겠음
Resolves: #159 
Resolves: #171
=> Feat: 비로그인 체크, 알럿 구현 / 메인셀 클릭 시 유저체크

Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/ReportVC.swift
DetailVC 의 코드내 노란색 경고 삭제
ReportVC의 코드 내 노란색 경고문 삭제 및 하이라이키 보라색 경고문 삭제
- DetailVC 파일 수정
- ReportVC 파일수정
- DetailVC 의 코드내 노란색 경고 삭제
- ReportVC의 코드 내 노란색 경고문 삭제 및 하이라이키 보라색 경고문 삭제
Resolves: #178
=> Fix : DetailVC, ReportVC 경고문 삭제

Ting/Post/PostView/PostDetailVC.swift
=> Fix : DetailVC 신고하기 버튼 수정

Ting/Post/PostView/ReportVC.swift
- 신고하기 뷰에서 키보드가 내려가지 않는 문제 해결
- 다른 공간 터치시 키보드 내려가지 않는 문제 해결
#Resolves: #185
=> Fix: 신고하기 뷰에서 키보드가 내려가지 않는 문제 해결

Ting/Extension/SpacesAndSpecialChar.swift, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/EditInfo/EditCustomView.swift, Ting/MyPage/EditInfo/EditInfoVC.swift, Ting/SignUp/SignUpView/SignUpView.swift
| 수정 전 | 수정 후 |
|:-------------------------:|:-------------------------:|
| <img width="324" alt="스크린샷 2025-02-12 오후 10 56 59" src="https://github.com/user-attachments/assets/3ae7ed10-5af1-457d-8f6d-29b0e0e15271"> <br>  | <img width="325" alt="스크린샷 2025-02-12 오후 10 57 31" src="https://github.com/user-attachments/assets/9504ac3c-1672-47c1-b928-0ebc2254c198"> <br>  |
---
- 순수 공백만, 텍스트 사이에, 텍스트 끝에. 어떠한 조건이라도 공백이 있으면 Alert을 출력.
- 순수 특수문자만, 텍스트 사이에, 텍스트 끝에. 어떠한 조건이라도 특수문자가 있으면 Alert을 출력.
- `extension`으로 따로 분리 구현하여 재사용성 및 코드 가독성을 높였습니다.
| 공백 | 텍스트 사이에 공백 |
|:-------------------------:|:-------------------------:|
| <img width="561" alt="스크린샷 2025-02-12 오후 11 04 17" src="https://github.com/user-attachments/assets/c9a77cc7-6652-4494-88a0-c40d883665ec"> <br>  | <img width="561" alt="스크린샷 …
=> Feat: TextField 공백추가, 공백, 특수문자 검사 로직 구현 및 추가

Ting/API/PostService.swift, Ting/API/UserInfoService.swift
- PostService 파일 수정
- UserInfoService 파일 수정
- 신고하기 버튼 터치시 신고하기 완료 이후 신고자는 신고한 게시글 못보게 기능 구현
- 누적 5 or 10회 누적된 신고 게시글은 자동삭제 기능 구현(바로 작업예정)
- 여러번 신고된 대상자에 한해서 C,U,D 기능 제한 기능 구현(추가 리젝시 구현)
Resolves: #208
=> Feat : 신고하기 버튼 터치시 해당 게시글 안보이게 적용

.gitignore, Ting.xcodeproj/project.pbxproj, Ting/Info.plist, Ting/Models/UserInfo.swift, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/EditInfo/EditInfoVC.swift, Ting/MyPage/MyPageMain/MyPageMainVC.swift
=> Fix: 지역 삭제

Ting.xcodeproj/project.pbxproj
=> Fix: project파일 쪽에서 불필요한 파일로 발생하는 오류 제거

Ting.xcodeproj/project.pbxproj
- 심사 신청때, APNs를 사용하지 않음에도 설정되어있는 부분이 있어서 해당 부분 삭제하였습니다.
=> Fix: APNs 관련 오류 삭제

Ting.xcodeproj/project.pbxproj, Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/EditInfo/EditCustomView.swift, Ting/MyPage/EditInfo/EditInfoVC.swift
- `TextField`들을 채울때, 키보드의 Return키를 next키로 변경.(마지막 필드는 Done)
- 클릭시 다음필드로 자동으로 넘어가게 구현, Done은 키보드가 사라지게 구현
- `기술 스택`, `사용 툴`필드의 글자수 제한을 20 -> 40으로 변경
Resolves: #229
=> Fix: 키보드 관련 수정, 일부 필드 글자수 변경

Ting/Post/PostView/JoinTeamUploadVC.swift, Ting/Post/PostView/PostDetailVC.swift, Ting/Post/PostView/PostListVC.swift, Ting/Post/PostView/RecruitMemberUploadVC.swift
- PostListVC
- PostDetailVC
- JoinTeamUploadVC
- RecruitMemberUploadVC
- 회원정보 수정시 ListVC 자동 업데이트
- 게시글 수정시 main, detail, listVC 자동 업데이트
=> Fix : 회원정보 수정시 리스트 변경 및 게시글 수정시 리스트 업데이트

Ting/Post/PostView/PostDetailVC.swift
- PostDetailVC 파일 수정
- 팀원 모집일 시 프로젝트 설명이라고 출력
- 팀 합류일 시 설명이라고 출력
Resolves: #235
=> Fix : 팀원모집 - 팁 합류간 출력내용 수정

Ting/MyPage/AddUserInfo/AddUserInfoVC.swift, Ting/MyPage/EditInfo/EditInfoVC.swift
- 기존 각 필드마다 다른 기준으로 공백, 특수문자, 첫문자 공백 등의 검증을 거쳤었는데
- 현재 닉네임을 제외하고 전부 첫문자가 공백인지만 체크하도록 로직을 변경하였습니다.
=> Fix: 첫 글자 공백인지만 검증하도록 검증 로직 수정
